version: '3'
services:
    memory-corruption:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "2000:2000"
            - "2001:2001"
            - "2002:2002"
            - "2003:2003"
